{
  config,
  pkgs,
  ...
}:
let
  python = pkgs.python3;
in
{
  programs.emacs = {
    enable = true;
    package = pkgs.emacs-macport;
    extraPackages =
      epkgs: with epkgs; [
        elisp-autofmt
        dashboard
        vertico
        consult
        vterm
        kkp
      ];
  };

  home.file.".config/emacs/init.el".source =
    config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/projects/dotfiles/emacs/init.el";

  home.file.".config/emacs/early-init.el".source =
    config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/projects/dotfiles/emacs/early-init.el";

  home.file.".config/emacs/nix-paths.el".text = ''
    ;;; nix-paths.el --- Nix-injected store paths -*- lexical-binding: t; -*-
    ;;; Commentary:
    ;; Generated by Home Manager (nix/modules/emacs.nix). Do not edit.
    ;;; Code:
    (setq elisp-autofmt-python-bin "${python}/bin/python3")
    (provide 'nix-paths)
    ;;; nix-paths.el ends here
  '';
}
